version: "3"
services:
  whatsapp_bot:
    image: ghcr.io/maikemota/whatsapp-bot:latest
    environment:
      - FCS_API_KEY=${FCS_API_KEY}
      - FCS_API_KEY_2=${FCS_API_KEY_2}
      - OPEN_WHEATER_KEY=${OPEN_WHEATER_KEY}
      - NODE_ENV=${NODE_ENV}
      - TZ=${TZ}
      - DEEPGRAM_APY=${DEEPGRAM_APY}
      - ALL_COMMAND_INTERVAL_IN_MINUTES=${ALL_COMMAND_INTERVAL_IN_MINUTES}
      - ALL_COMMAND_BANNED_USERS=${ALL_COMMAND_BANNED_USERS}
      - YOUTUBE_USER=${YOUTUBE_USER}
      - YOUTUBE_KEY=${YOUTUBE_KEY}
      - YT_STATISTICS_CACHE_TTL_IN_MINUTS=${YT_STATISTICS_CACHE_TTL_IN_MINUTS}
      - VDA_UPDATE_STATISTICS_EVERY_N_MINUTES=${VDA_UPDATE_STATISTICS_EVERY_N_MINUTES}
      - VDA_NOTIFY_EVERY_N_SUBSCRIBERS=${VDA_NOTIFY_EVERY_N_SUBSCRIBERS}
      - VDA_NOTIFY_EVERY_N_VIEWS=${VDA_NOTIFY_EVERY_N_VIEWS}
      - VDA_CHANNELS_TO_NOTIFY=${VDA_CHANNELS_TO_NOTIFY}
      - VDA_LINKS=${VDA_LINKS}
      - TEMP_FOLDER=${TEMP_FOLDER}
      - CARTEIRA_COMMAND_ALLOWED_CHATS=${CARTEIRA_COMMAND_ALLOWED_CHATS}
    volumes:
      - type: bind
        source: ${AUTH_FOLDER}
        target: /app/.wwebjs_auth
      - type: bind
        source: ${HOST_TEMP_FOLDER}
        target: /app/tmp
    restart: always

    
