version: "3.2"
services:
  whatsapp_bot:
    image: ghcr.io/maikemota/whatsapp-bot:latest
    environment:
      - FCS_API_KEYS=${FCS_API_KEYS}
      - BRAPI_KEY=${BRAPI_KEY}
      - OPEN_WHEATER_KEY=${OPEN_WHEATER_KEY}
      - NODE_ENV=${NODE_ENV}
      - TZ=${TZ}
      - DEEPGRAM_APY=${DEEPGRAM_APY}
      - ALL_COMMAND_INTERVAL_IN_MINUTES=${ALL_COMMAND_INTERVAL_IN_MINUTES}
      - ALL_COMMAND_BANNED_USERS=${ALL_COMMAND_BANNED_USERS}
      - YOUTUBE_USER=${YOUTUBE_USER}
      - YOUTUBE_KEY=${YOUTUBE_KEY}
      - YT_STATISTICS_CACHE_TTL_IN_MINUTS=${YT_STATISTICS_CACHE_TTL_IN_MINUTS}
      - VDA_UPDATE_STATISTICS_EVERY_N_MINUTES=${VDA_UPDATE_STATISTICS_EVERY_N_MINUTES}
      - VDA_NOTIFY_EVERY_N_SUBSCRIBERS=${VDA_NOTIFY_EVERY_N_SUBSCRIBERS}
      - VDA_NOTIFY_EVERY_N_VIEWS=${VDA_NOTIFY_EVERY_N_VIEWS}
      - VDA_CHANNELS_TO_NOTIFY=${VDA_CHANNELS_TO_NOTIFY}
      - VDA_LINKS=${VDA_LINKS}
      - TEMP_FOLDER=${TEMP_FOLDER}
      - CARTEIRA_COMMAND_ALLOWED_CHATS=${CARTEIRA_COMMAND_ALLOWED_CHATS}      
      - REACTIONS=${REACTIONS}
      - CHATGROUPS=${CHATGROUPS}
      - RADAR_PREFERIDAS_UPDATE_IN_HOURS=${RADAR_PREFERIDAS_UPDATE_IN_HOURS}
      - WCLIENT_ID=${WCLIENT_ID}
      - USE_WEB_CACHE_VERSION=${USE_WEB_CACHE_VERSION}
      - RANDOM_ORG_API_KEYS=${RANDOM_ORG_API_KEYS}
      - EMMA_TRACKING_CODE=${EMMA_TRACKING_CODE}
      - EMMA_TRACKER_CHAT_IDS=${EMMA_TRACKER_CHAT_IDS}
    volumes:
      - type: bind
        source: ${AUTH_FOLDER}
        target: /app/auth_data
      - type: bind
        source: ${HOST_TEMP_FOLDER}
        target: /app/tmp
    restart: always

    
